export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT = "LOGOUT";

export const GET_FILTERED_JOURNEYS = "GET_FILTERED_JOURNEYS";
export const GET_JOURNEY = "GET_JOURNEY";
export const CREATE_JOURNEY = "CREATE_JOURNEY";
export const JOURNEY_ERROR = "JOURNEY_ERROR";
export const GET_OWN_JOURNEY = "GET_OWN_JOURNEY";
export const CANCEL_JOURNEY = "CANCEL_JOURNEY";

//Spinner
export const SPINNER_LOADING = "SPINNER_LOADING";
export const SPINNER_LOADED = "SPINNER_LOADED";

// demands
export const GET_OWN_JOURNEY_DEMANDS = "GET_OWN_JOURNEY_DEMANDS";
export const JOURNEY_DEMANDS_ERROR = "JOURNEY_DEMANDS_ERROR";
